//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1001.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string ContentID { get; set; }
        public int SectionID { get; set; }
        public int ComponentID { get; set; }
        public string Data { get; set; }
        public bool Inactive { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
