//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1001.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaAsset
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public byte Type { get; set; }
        public bool IsExternal { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
