//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1001.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFileTask
    {
        public int ID { get; set; }
        public string PIDs { get; set; }
        public string CIDs { get; set; }
        public int Status { get; set; }
        public string EmailTo { get; set; }
        public string ConvertedFilePath { get; set; }
        public string Description { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<System.DateTime> ConvertedDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    }
}
