//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1001.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Components = new HashSet<Component>();
        }
    
        public int ID { get; set; }
        public int CreatedBy { get; set; }
        public bool Archived { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ArchivedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Component> Components { get; set; }
    }
}
